### ISSUE TITLE
Wave Editor Crashes

### ISSUE THREAD

**Issue by stnight** [WaveEngine/Documentation#1]
I tried to start to run the Wave Editor, but every time i login it crashes. Please help.

OS: Elementary OS (based from ubuntu 14.10)
RAM: 12 GB

**Comment by stnight** [comment]
Is anyone investigating on this?

**Comment by juanlao** [comment]
Please, feel free to use the forums http://forum.waveengine.net/ for report bugs and crashes.

Thanks!
